Hackathon.Website/Controllers/ChatController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Services;
using Hackathon.Models.View;

namespace Hackathon.Website.Controllers
{
    public class ChatController : Controller
    {
        private const string Key = "ChatUsers";

        public ActionResult Index()
        {
            var viewModel = new ChatViewModel();
            return View(viewModel);
        }

        [WebMethod]
        public JsonResult Login(string name)
        {
            name = name.Trim().ToLower();

            var userList = HttpContext.Cache[Key] as List<string> ?? new List<string>();

            if (userList.Contains(name))
                return Json(false, JsonRequestBehavior.AllowGet);

            userList.Add(name);

            HttpContext.Cache[Key] = userList;

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult UserExists(string name)
        {
            name = name.Trim().ToLower();

            var userList = HttpContext.Cache[Key] as List<string> ?? new List<string>();

            var exists = userList.Count > 0 && userList.Contains(name);

            return Json(exists, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult GetAllUsers()
        {
            var userList = HttpContext.Cache[Key] as List<string> ?? new List<string>();

            return Json(userList, JsonRequestBehavior.AllowGet);
        }
    }
}

Hackathon.Website/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Hackathon.Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hackathon.Website/Controllers/StackOverflowController.cs
using System;
using System.Net;
using System.Web.Mvc;
using System.Web.Services;

namespace Hackathon.Website.Controllers
{
    public class StackOverflowController : Controller
    {
        [WebMethod]
        public JsonResult GetStackQuestions(string tag)
        {
            try
            {
                using (var webClient = new WebClient())
                {
                    var response = webClient.DownloadString("https://api.stackexchange.com/docs/search#order=desc&sort=activity&filter=default&site=stackoverflow&tagged=" + tag);

                    return Json(response, JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception exception)
            {
                return Json(exception.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Hackathon.Website/Controllers/TwitterController.cs
using System.Web.Mvc;
using System.Web.Services;
using Hackathon.Models.Helper;
using TweetSharp;

namespace Hackathon.Website.Controllers
{
    public class TwitterController : Controller
    {
        public ActionResult Authorize()
        {
            var twitterService = new TwitterService(TwitterAuthentication.Key, TwitterAuthentication.Secret);

            var requestToken = twitterService.GetRequestToken();

            Session["RequestToken"] = requestToken;

            var uri = twitterService.GetAuthorizationUri(requestToken);

            return new RedirectResult(uri.ToString());
        }

        [WebMethod]
        public JsonResult AuthorizeCallback(string verificationCode)
        {
            var requestToken = Session["RequestToken"] as OAuthRequestToken;

            if (requestToken == null)
                return Json(false, JsonRequestBehavior.AllowGet);

            var service = new TwitterService(TwitterAuthentication.Key, TwitterAuthentication.Secret);

            var accessToken = service.GetAccessToken(requestToken, verificationCode);
            
            Session["AccessToken"] = accessToken;

            service.AuthenticateWith(accessToken.Token, accessToken.TokenSecret);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult IsAuthorized()
        {
            var authorized = GetAuthenticatedService() != null;

            return Json(authorized, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult GetTweets(int page)
        {
            var service = GetAuthenticatedService();

            if (service == null)
                return Json(false, JsonRequestBehavior.AllowGet);

            var tweets = service.ListTweetsOnHomeTimeline(page, 10);

            return Json(tweets, JsonRequestBehavior.AllowGet);
        }

        private TwitterService GetAuthenticatedService()
        {
            try
            {
                var service = new TwitterService(TwitterAuthentication.Key, TwitterAuthentication.Secret);

                var accessToken = Session["AccessToken"] as OAuthAccessToken;

                if (accessToken == null)
                    return null;

                service.AuthenticateWith(accessToken.Token, accessToken.TokenSecret);

                var twitterUser = service.VerifyCredentials();

                return twitterUser == null ? null : service;
            }
            catch
            {
                return null;
            }
        }
    }
}

Hackathon.Website/Views/Chat/ChatFeed.cshtml
<div data-bind="if: chatEnabled">
    <div class="control-group">
        <div class="controls">
            <ul data-bind="foreach: users" class="user-list">
                <li data-bind="text: name" class="btn"></li>        
            </ul>
            <input type="text" id="Message" class="span4" placeholder="Enter a message..." />
            <br />
            <a id="Send" class="btn">Send</a>
            <p class="help-block"></p>
            <ul data-bind="foreach: messages" class="message-list">
                <li data-bind="html: renderMessage"></li>
            </ul>
        </div>
    </div>
</div>

<div data-bind="ifnot: chatEnabled">
    <div class="control-group">
        <div class="controls">
            <p>Please login to chat</p>
            <input type="text" id="ChatLoginInput" class="span4" placeholder="What's your name?" />
            <br />
            <a id="ChatLoginButton" class="btn add-on">Login</a>
            <p class="help-block"></p>
        </div>
    </div>
</div>

Hackathon.Website/Views/Chat/Index.cshtml
@model Hackathon.Models.View.ChatViewModel
@{
    ViewBag.Title = "...";
}

<div class="row-fluid">

    <div class="span4 chat-col">
        
        <div class="well">
        
            <h2>Chat</h2>
    
            @Html.Partial("ChatFeed")

        </div>

    </div>

    <div class="span4 twitter-col">
        
        <div class="well">

            <h2>Twitter</h2>
    
            @Html.Partial("TwitterFeed")

        </div>
    
    </div>

    <div class="span4 yammer-col">
        
        <div class="well">
        
            <h2>StackOverflow</h2>
    
            @Html.Partial("StackFeed")

        </div>
    
    </div>

</div>

Hackathon.Website/Views/Chat/StackFeed.cshtml
<p>Search for a question</p>
<input type="text" id="SearchInput" class="span4" placeholder="Searching for?" />
<br />
<a id="SeachGo" class="btn">Search</a>
<p class="help-block"></p>
<ul data-bind="foreach: questions" class="question-list">
    <li data-bind=""></li>
</ul>

Hackathon.Website/Views/Chat/TwitterFeed.cshtml
@model Hackathon.Models.View.ChatViewModel

<div data-bind="if: twitterLoading">

    <br />
    <img src="@Url.Content("~/Content/images/loading.gif")" alt="Loading!" />

</div>

<div data-bind="ifnot: twitterLoading">

    <div data-bind="if: twitterEnabled">
        <ul data-bind='foreach: tweets' class="twitter-feed">
            <li>
                <div class="avatar" data-bind="html: renderImage"></div>
                <div class="name" data-bind="html: renderLink"></div>
                <div class="text" data-bind="html: renderText"></div>
            </li>
        </ul>
        <a id="LoadMoreTweets" class="btn btn-large">Load more tweets</a>
        <img id="LoadingMore" class="loading" src="@Url.Content("~/Content/images/loading.gif")" alt="Loading!" />
    </div>

    <div data-bind="ifnot: twitterEnabled">
        <div class="control-group">
            <div class="controls">
                <p>You need to @Html.ActionLink("enable Twitter.", "Authorize", "Twitter", null, new { target = "_blank" })</p>
                <input type="text" id="AuthorizeInput" class="span4" placeholder="Enter Twitter verification code..." />
                <br />
                <a id="AuthorizeButton" class="btn">Submit</a>
                <img id="LoadingLogin" class="loading" src="@Url.Content("~/Content/images/loading.gif")" alt="Loading!" />
                <p class="help-block"></p>
            </div>
        </div>
    </div>

</div>

Hackathon.Website/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Hackathon.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <div id="LoadingModal">
        <div id="Animation"></div>
    </div>
    <script type='text/javascript' src='https://api.stackexchange.com/js/2.0/all.js'></script>
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.signalR.min.js")"></script>
    <script src="@Url.Content("~/Scripts/knockout.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/chat.js")"></script>
</body>
</html>